iaas_settings:
  <<: (( merge || nil ))
  additional_resource_pools:
  - name: monitoring
    network: mysql1
    cloud_properties: {}
    stemcell: (( iaas_settings.stemcell ))

  additional_disk_pools: []
